---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iacdemo
    app.kubernetes.io/version: "1.0"
  name: iacdemo
  namespace: default
spec:
  ports:
    - name: http
      nodePort: 31382
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: iacdemo
    app.kubernetes.io/version: "1.0"
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iacdemo
    app.kubernetes.io/version: "1.0"
  name: iacdemo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iacdemo
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iacdemo
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_JDBC
              value: 'jdbc:postgresql://iacdemo-master.cdq4th9p3twq.us-west-2.rds.amazonaws.com:5432/postgres'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: iacdemo
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: iacdemo
                  key: password
          image: kkokkino/iacdemo:1.0
          imagePullPolicy: IfNotPresent
          name: iacdemo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
